server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  # Loki будет доступен по имени сервиса внутри сети Docker Compose
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: xednix-app
          __path__: /var/log/xednix_app/*.log # Путь, куда Flask будет писать логи