"""Added ApplicantProfile and Skill models

Revision ID: f27a5c064ac5
Revises: a210b141d595
Create Date: 2025-09-27 08:52:33.173674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27a5c064ac5'
down_revision = 'a210b141d595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_focus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=False),
    sa.Column('target_level', sa.String(length=50), nullable=False),
    sa.Column('focused_skills_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['applicant_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_focus')
    # ### end Alembic commands ###
